# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1014be2cc479fd5e030caa01c49d01db8401e5147f51958e32a2ffa0d17257c77e82b66ab9b285215830ae3db37c9297f255bf172ca3fcc0bff7194dcfa59ef

test:
  secret_key_base: 5371c835f272763a28a79d11fb634359ca58c5c2b2031360a77ab8deae2af815fe16dabd3d4400f2aaae51d387cd60fc7d3198bb5964cd06ba2527601df4d020

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
